# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.0.0-beta.42" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.0.0-beta.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.0.0-beta.42.tgz";
        sha512 = "24mqcb4f2a0vncmigl9kj0nmi9bwfhi2rs6pab1b37kdvsc1d1qk220nnhxdswpcg8335ps4j076rnydz355qrbk2nv6d0f9b6r3qc8";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "base64url-2.0.0" = {
      name = "base64url";
      packageName = "base64url";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64url/-/base64url-2.0.0.tgz";
        sha1 = "eac16e03ea1438eff9423d69baa36262ed1f70bb";
      };
    };
    "core-js-1.2.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz";
        sha1 = "652294c14651db28fa93bd2d5ff2983a4f08c636";
      };
    };
    "core-js-2.5.3" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.3.tgz";
        sha1 = "8acc38345824f16d8365b7c9b4259168e8ed603e";
      };
    };
    "deep-diff-0.3.8" = {
      name = "deep-diff";
      packageName = "deep-diff";
      version = "0.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-diff/-/deep-diff-0.3.8.tgz";
        sha1 = "c01de63efb0eec9798801d40c7e0dae25b582c84";
      };
    };
    "encoding-0.1.12" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.12.tgz";
        sha1 = "538b66f3ee62cd1ab51ec323829d1f9480c74beb";
      };
    };
    "fbjs-0.8.16" = {
      name = "fbjs";
      packageName = "fbjs";
      version = "0.8.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/fbjs/-/fbjs-0.8.16.tgz";
        sha1 = "5e67432f550dc41b572bf55847b8aca64e5337db";
      };
    };
    "hoist-non-react-statics-2.5.0" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-2.5.0.tgz";
        sha512 = "3bvgj9sbamk2kv7p7s0ham8apqqpksjnkrb61h5kd5hbsl6hzydqibk4m7sljgfmax9w6ayr4cqz79az0d25nsis927pmnkq1g7l6g8";
      };
    };
    "i18n-iso-countries-3.6.1" = {
      name = "i18n-iso-countries";
      packageName = "i18n-iso-countries";
      version = "3.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/i18n-iso-countries/-/i18n-iso-countries-3.6.1.tgz";
        sha512 = "25j0chkn2b6x4vgrww1hrv60mwjg5iylamrgr5j87vzvbryq7w9vkbcyiiq3f6xssqzrl4q389n5sfvxrq44l96pscdggsks1jhg2p5";
      };
    };
    "iconv-lite-0.4.19" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.19.tgz";
        sha512 = "0jj1pdq3j9ak8cixn2kjp7ip8hf3xgnb85j4jr32yf9rry620v9072c0kk577mllfk1zl9wzs5ypwzbp7vbhf7j31d5rrqgwb0nldm1";
      };
    };
    "invariant-2.2.4" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
        sha512 = "0sa0bflh46zr7zqdifqk3a48bmqlmpikrnmwvgz8nx6979piw2m92qrn1g5xnpjzxn864y2jq3gl84jkws2dad3mlwr6s3fa10my4m6";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "isomorphic-fetch-2.2.1" = {
      name = "isomorphic-fetch";
      packageName = "isomorphic-fetch";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-2.2.1.tgz";
        sha1 = "611ae1acf14f5e81f729507472819fe9733558a9";
      };
    };
    "js-tokens-3.0.2" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz";
        sha1 = "9866df395102130e38f7f996bceb65443209c25b";
      };
    };
    "langs-2.0.0" = {
      name = "langs";
      packageName = "langs";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/langs/-/langs-2.0.0.tgz";
        sha1 = "00c32ce48152a49a614450b9ba2632ab58a0a364";
      };
    };
    "lodash-4.17.5" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.5.tgz";
        sha512 = "11hikgyas884mz8a58vyixaahxbpdwljdw4cb6qp15xa3sfqikp2mm6wgv41jsl34nzsv1hkx9kw3nwczvas5p73whirmaz4sxggwmj";
      };
    };
    "lodash-es-4.17.7" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.7.tgz";
        sha512 = "1rrja9hyj2jp90mvw5phx9b1nz03r76v1mx7bahzngbls1ddzvjpvd3sdhx3734cdl2q7nb6c51zsfiq7c70dxfqr1rxq74gf5r6flg";
      };
    };
    "loose-envify-1.3.1" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.3.1.tgz";
        sha1 = "d1a8ad33fa9ce0e713d65fdd0ac8b748d478c848";
      };
    };
    "node-fetch-1.7.3" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-1.7.3.tgz";
        sha512 = "0lz5m15w7qaks0a0s3dm0crsjrsd123dy00pn6qwcp50zfjykxkp22i5ymh6smlc0ags38nmdxlxw9yyq509azlv8kcdvdiq857h5in";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "17cn4nns2nxh9r0pdiqsqx3fpvaa82c1mhcr8r84k2a9hkpb0mj4bxzfbg3l9iy74yn9hj6mh2gsddsi3v939a1zp7ycbzqkxfm12cy";
      };
    };
    "prop-types-15.6.1" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.6.1.tgz";
        sha512 = "28vp2j7wpa97ygi4clflilfs8wj8qsz1x3fismsqx293a9cvpyc20k4pbrppyn7y6hks0dp3mn0wmj5q3y1y3i5k7ra5ssqimnkprz1";
      };
    };
    "react-16.2.0" = {
      name = "react";
      packageName = "react";
      version = "16.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.2.0.tgz";
        sha512 = "06jpx4ipg4fqmn52gz95i8hn5m5hvhz48pnqkq9c045xzwyabsdd5p9qij10x79xm3hzr356bvnrmczv40i9lj97kpm04y4rsc2hqk6";
      };
    };
    "react-dom-16.2.0" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.2.0.tgz";
        sha512 = "27fzqr9bpraww7c66rib1znjqyj6jrpsrhw94zqmbgjlgfbkrylyq5x1anm7bmx2h0w5qbwha7anjj7zqdglpfxsfsd57ym05vq14ff";
      };
    };
    "react-redux-5.0.7" = {
      name = "react-redux";
      packageName = "react-redux";
      version = "5.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-redux/-/react-redux-5.0.7.tgz";
        sha512 = "231jvmg1dgkp31sfl0czszkz77sag822nlcznpmh28cgzk3r3c8rkfcwdyihv2d5a9mqajinn999fknbcq5pripr9h06xk1bq8kqlp5";
      };
    };
    "redux-3.7.2" = {
      name = "redux";
      packageName = "redux";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux/-/redux-3.7.2.tgz";
        sha512 = "3wb0gl46i4d7zr5bdm38g1a7a5j179ww8wa22wy3z3vknvpipddh1ba2w7cfkirqjg2jc69dxjhcy02vcyr4hcl3m3qx15mv9zsgnm4";
      };
    };
    "redux-localstorage-0.4.1" = {
      name = "redux-localstorage";
      packageName = "redux-localstorage";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-localstorage/-/redux-localstorage-0.4.1.tgz";
        sha1 = "faf6d719c581397294d811473ffcedee065c933c";
      };
    };
    "redux-logger-3.0.6" = {
      name = "redux-logger";
      packageName = "redux-logger";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-logger/-/redux-logger-3.0.6.tgz";
        sha1 = "f7555966f3098f3c88604c449cf0baf5778274bf";
      };
    };
    "redux-thunk-2.2.0" = {
      name = "redux-thunk";
      packageName = "redux-thunk";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-thunk/-/redux-thunk-2.2.0.tgz";
        sha1 = "e615a16e16b47a19a515766133d1e3e99b7852e5";
      };
    };
    "regenerator-runtime-0.11.1" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz";
        sha512 = "03d4l8l8cyywh93wf5vw84lq56jh1b1d7jll4ny4z060j9hvx7w5q3q0b8q227jm93749k1c9h86r2pz0bm2xq5vp14g3r2kbvqc2rj";
      };
    };
    "setimmediate-1.0.5" = {
      name = "setimmediate";
      packageName = "setimmediate";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz";
        sha1 = "290cbb232e306942d7d7ea9b83732ab7856f8285";
      };
    };
    "symbol-observable-1.2.0" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.2.0.tgz";
        sha512 = "1fxqjwdn747lxzkxrwhbw8arc9czdig47izx5hnzk22z8k7rnw00q8vcpy8v7a3xyamavwgg4mvjkpn2ihjiyjxjnhx2ihiryf39pbv";
      };
    };
    "ua-parser-js-0.7.17" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.17.tgz";
        sha512 = "39ac4xrr9v9ya7rbn5cz8dss5j3s36yhpj9qrhfxxqzgy1vljns0qfyv7d76lqgdgdbfbrd91kb5x7jlg0fw2r4f3kml0v8xmv545xr";
      };
    };
    "whatwg-fetch-2.0.3" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-2.0.3.tgz";
        sha1 = "9c84ec2dcf68187ff00bc64e1274b442176e1c84";
      };
    };
  };
  args = {
    name = "facebook-ad-extension";
    packageName = "facebook-ad-extension";
    version = "1.0.0";
    src = ../extension;
    dependencies = [
      sources."@babel/runtime-7.0.0-beta.42"
      sources."asap-2.0.6"
      sources."base64url-2.0.0"
      sources."core-js-2.5.3"
      sources."deep-diff-0.3.8"
      sources."encoding-0.1.12"
      (sources."fbjs-0.8.16" // {
        dependencies = [
          sources."core-js-1.2.7"
        ];
      })
      sources."hoist-non-react-statics-2.5.0"
      sources."i18n-iso-countries-3.6.1"
      sources."iconv-lite-0.4.19"
      sources."invariant-2.2.4"
      sources."is-stream-1.1.0"
      sources."isomorphic-fetch-2.2.1"
      sources."js-tokens-3.0.2"
      sources."langs-2.0.0"
      sources."lodash-4.17.5"
      sources."lodash-es-4.17.7"
      sources."loose-envify-1.3.1"
      sources."node-fetch-1.7.3"
      sources."object-assign-4.1.1"
      sources."promise-7.3.1"
      sources."prop-types-15.6.1"
      sources."react-16.2.0"
      sources."react-dom-16.2.0"
      sources."react-redux-5.0.7"
      sources."redux-3.7.2"
      sources."redux-localstorage-0.4.1"
      sources."redux-logger-3.0.6"
      sources."redux-thunk-2.2.0"
      sources."regenerator-runtime-0.11.1"
      sources."setimmediate-1.0.5"
      sources."symbol-observable-1.2.0"
      sources."ua-parser-js-0.7.17"
      sources."whatwg-fetch-2.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}